### ISSUE TITLE
Нужна помощь

### ISSUE THREAD

**Issue by j3tson** [avgsr/atol2108#2]
Добрый день. Тоже попал с этими чеками без реквизита 2108. Если есть возможность, свяжитесь пожалуйста со мной в TG @wujins

**Comment by avgsr** [comment]
чем помочь?

**Comment by j3tson** [comment]
Помогите пожалуйста подогнать скрипты под мою ситуацию, разумеется на возмездной основе. У вас есть телеграм или как по другому можно с Вами связаться?

**Comment by avgsr** [comment]
> Помогите пожалуйста подогнать скрипты под мою ситуацию, разумеется на возмездной основе. У вас есть телеграм или как по другому можно с Вами связаться?

написал в тг
